### ISSUE TITLE
opustools build is failing on MacOS

### ISSUE THREAD

**Issue by ixchow** [15-466/nest-libs#1]
Log snippets from github actions:

```
2020-03-08T03:46:22.2934660Z checking for clock_nanosleep... no
2020-03-08T03:46:22.2950400Z checking for pkg-config... no
2020-03-08T03:46:22.2964740Z checking for pkg-config... no
2020-03-08T03:46:22.3705770Z checking for Ogg... no
2020-03-08T03:46:22.3706050Z *** Could not run Ogg test program, checking why...
2020-03-08T03:46:22.4283850Z *** The test program failed to compile or link. See the file config.log for the
2020-03-08T03:46:22.4284130Z *** exact error that occured. This usually means Ogg was incorrectly installed
2020-03-08T03:46:22.4284250Z *** or that you have moved Ogg since it was installed.
2020-03-08T03:46:22.4307900Z configure: error: 
2020-03-08T03:46:22.4308070Z     libogg is required to build this package!
2020-03-08T03:46:22.4308260Z     Please see https://www.xiph.org/ for how to obtain a copy.
```
and
```
2020-03-08T03:46:22.4815310Z Building opus-tools...
2020-03-08T03:46:22.4815840Z   Running `"./configure" "--prefix=/Users/runner/runners/2.165.2/work/nest-libs/nest-libs/work/opus-tools-0.2/out" "--disable-dependency-tracking" "--without-flac" "--enable-sse"`
2020-03-08T03:46:22.4996400Z Traceback (most recent call last):
2020-03-08T03:46:22.4997400Z   File "rebuild-libs.py", line 918, in <module>
2020-03-08T03:46:22.4997850Z     build_opustools()
2020-03-08T03:46:22.4998400Z   File "rebuild-libs.py", line 763, in build_opustools
2020-03-08T03:46:22.4998510Z     ], env=env, cwd=lib_dir);
2020-03-08T03:46:22.4998960Z   File "rebuild-libs.py", line 96, in run_command
2020-03-08T03:46:22.4999070Z     subprocess.run(args,cwd=cwd,check=True,env=env)
2020-03-08T03:46:22.4999200Z   File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 512, in run
2020-03-08T03:46:22.4999320Z     output=stdout, stderr=stderr)
2020-03-08T03:46:22.4999930Z subprocess.CalledProcessError: Command '['./configure', '--prefix=/Users/runner/runners/2.165.2/work/nest-libs/nest-libs/work/opus-tools-0.2/out', '--disable-dependency-tracking', '--without-flac', '--enable-sse']' returned non-zero exit status 1.
```

**Comment by ixchow** [comment]
Appears to have been resolved.
